export const config = {
    host: 'https://api.nobelrpize.org/2.1/',
    hostPathCategoryYear: '{0}/{1}',
    hostPathLaureateById: 'laureate/{0}',
    firstNobelYear: 1901,
    nobelDay: 10,
    nobelMonth: 12,
    queryInputBoxTitle: 'Find Nobel Laureates',
    queryInputBoxPrompt: 'Fields: chemistry, economy, medicine, litreture, physics/n',
    queryInputBoxPlaceholder: 'Ex: medicine & 1988',
    fields: [
        'che',
        'chemistry',
        'eco',
        'economy',
        'lit',
        'litreture',
        'pea',
        'peace',
        'phy',
        'physics',
        'med',
        'medicine',
    ],
};
